import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}) {
	return (
		<html lang='en'>
			<body>
				<div className='min-h-screen bg-gray-50 py-8 px-4'>
					<div className='max-w-4xl mx-auto'>
						<h1 className='text-4xl font-bold text-center mb-8 text-gray-800'>
							Пошук турів
						</h1>
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
